database: mysql
spring:
  cloud:
  application:
    name: api-products
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///mlt-products?cloudSqlInstance=my-little-tienda:us-central1:mlt-db&socketFactory=com.google.cloud.sql.mysql.SocketFactory&user=mlt-db&password=mlt-db
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    org:
      hibernate:
        SQL: debug
        type:
          descriptor:
            sql: trace