--liquibase formatted sql
--changeset RustyCrazyPunky:create-tables
CREATE TABLE IF NOT EXISTS CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(1000) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PRICE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
    PRICE DOUBLE NOT NULL,
    CONSTRAINT PRICE_IBFK_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_CATEGORY (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    CATEGORY_ID INT NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
    CONSTRAINT PRODUCT_CATEGORY_IBFK_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID),
    CONSTRAINT PRODUCT_CATEGORY_IBFK_2 FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY (ID)
);

CREATE TABLE IF NOT EXISTS PRODUCT_IMAGE (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID INT NOT NULL,
    IMAGE_LINK VARCHAR(250) NOT NULL,
    CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP NULL,
    UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PROVIDER VARCHAR(100) NOT NULL,
    CONSTRAINT PRODUCT_IMAGE_IBFK_1 FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT (ID)
);