--liquibase formatted sql
--changeset RustyCrazyPunky:update-tables
ALTER TABLE PRODUCT ADD COLUMN DELETED_AT TIMESTAMP;

ALTER TABLE CATEGORY ADD COLUMN DELETED_AT TIMESTAMP;

ALTER TABLE PRICE ADD COLUMN DELETED_AT TIMESTAMP;

ALTER TABLE PRODUCT_CATEGORY ADD DELETED_AT TIMESTAMP NULL;

ALTER TABLE PRODUCT_IMAGE ADD DELETED_AT TIMESTAMP NULL;